### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ehsan-ej** [yonathan95/BinanceTradingBot#27]
Exception: java.lang.NumberFormatException: For input string: "6;"
Exception in thread "main" java.lang.ExceptionInInitializerError
	at data.AccountBalance.getAccountBalance(AccountBalance.java:38)
	at Main.main(Main.java:12)
Caused by: com.binance.client.exception.BinanceApiException: [Executing] -2014: API-key format invalid.
	at com.binance.client.impl.RestApiInvoker.checkResponse(RestApiInvoker.java:38)
	at com.binance.client.impl.RestApiInvoker.callSync(RestApiInvoker.java:65)
	at com.binance.client.impl.SyncRequestImpl.getAccountInformation(SyncRequestImpl.java:186)
	at data.AccountBalance.<init>(AccountBalance.java:31)
	at data.AccountBalance.<init>(AccountBalance.java:17)
	at data.AccountBalance$AccountBalanceHolder.<clinit>(AccountBalance.java:24)
	... 2 more
	
	
	can you help me to run your bot?

**Comment by nice7677** [comment]
Remove “”; only string

**Comment by ricardospinoza** [comment]
https://github.com/yonathan95/BinanceTradingBot/pull/88
